### ISSUE TITLE
Cannot open Isaac's PSA (particularly U.N Owen's)

### ISSUE THREAD

**Issue by TheSmashBoy** [Project-M-CC/isaac#2]
Does anyone here find it odd that 75% of the forbidden four can have their FitCharacter.pac files opened in the PSA program but the moment I open up Isaac's I get: "Could not locate data" and "Unable to unpack file". Is this common or is it just me? Or is it the PSA? Has anyone had such experience before? Please help.

**Comment by KorytheMaril** [comment]
I didn't have this issue, actually. It loaded just fine for me. The glaring issue I had was the model completely screwing up randomly in a match. I have no idea how you guys managed to get these characters to work in BrawlEX without having to conflict with Subspace Emissary files, but if I could figure it out, I could maybe root out the conflict.

**Comment by TheSmashBoy** [comment]
@KorytheMaril Well my problem is with opening his file in the PSA program not the game itself. Although it's great you could find a way to get it to work on the BrawlEx. 

 bb010g got it to work. He just hasn't tested U.N Owen's PSA in BrawlEx. If you'd like, you could test that and report the results at this repo or at Vector.

**Comment by KorytheMaril** [comment]
@TheSmashBoy I could certainly give it a shot; however, I'm not sure if I'd be the best to test it out; I'm very easily startled when it comes to model glitches.

**Comment by TheSmashBoy** [comment]
@KorytheMaril Alright. I guess this needs further investigation. We just recently exported these characters to BEX format. So in a sense; we just have started over from a BrawlEx template. A lot of work has to be done to adapt these characters to BrawlEx templates.

**Comment by TheSmashBoy** [comment]
Closing as you need BrawlBox 0.67b to open it. Apparently its PSA was made in a way it is only accessible through an older version of BrawlBox with the PSA loader.

**Comment by bb010g** [comment]
@TheSmashBoy Do you have any more info about that? I'd think that would be something worth an issue report if we can nail it down.

**Comment by TheSmashBoy** [comment]
@bb010g Again, I was able to open it in earlier versions of BrawlBox like 0.68b or 0.67b. Another example is a Lucina PSA from crazyhandmasterhand. I was able to open it in BrawlBox but not in the PSA program.
